In [1]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

1.1.0


In [3]:
torch.cuda.is_available()

True

In [4]:
torch.version.cuda

'9.0.176'

In [5]:
t = torch.tensor([1, 3, 4]).cuda()
t

tensor([1, 3, 4], device='cuda:0')

In [6]:
t_new = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [7]:
t_new = torch.tensor(t_new)

In [8]:
t_new = t_new.reshape(4, 2)
t_new.shape

torch.Size([4, 2])

In [9]:
t = torch.Tensor()
type(t)

torch.Tensor

In [10]:
print(t.dtype) # the type of data contained in the tensor
print(t.device) # where the tensor conputation of the tensor will be performed 
print(t.layout) # how tensor instance ia laid out in memory

torch.float32
cpu
torch.strided


In [11]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [12]:
data = np.array([1, 2, 3])
type(data)

numpy.ndarray

In [13]:
torch.Tensor(data) # data type is converted from int to float

tensor([1., 2., 3.])

In [14]:
# Tensor() is a constructor function
# tensor() is a factory function that builds tensors for us

torch.tensor(data) 

tensor([1, 2, 3])

In [15]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [16]:
torch.from_numpy(data)

tensor([1, 2, 3])

In [17]:
# only need to specify the number of rows
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [18]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [19]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [20]:
torch.rand(2, 2)

tensor([[0.8269, 0.7958],
        [0.1674, 0.5044]])

In [21]:
torch.get_default_dtype()

torch.float32

In [22]:
torch.tensor(np.array([1, 2, 3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

Tensor operation types
1. Reshaping operations
2. Element-wise operations
3. Reduction operations
4. Access operations

In [23]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2], 
    [3,3,3,3]
], dtype=torch.float32)

In [24]:
t.size()

torch.Size([3, 4])

In [25]:
t.shape

torch.Size([3, 4])

In [26]:
len(t.shape)

2

In [28]:
# Return the number of elements by calling prod() to make a product

torch.tensor(t.shape).prod()

tensor(12)

In [30]:
# stands for number of elements
# the number of elements maters because reshaping must contain these elements

t.numel()

12

In [32]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [34]:
# squeeze() removes all axises that have the length of 1

print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [39]:
# unsqueeze() adds an axis with a length of 1

print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [45]:
def flatten(t):
    t = t.reshape(1,-1) # just flatten still have two axises (create an axis with length 1)
    t = t.squeeze() # remove the axis with length of 1 leave just in one dimension
    return t

In [46]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [47]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])

In [48]:
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [49]:
torch.cat((t1, t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [50]:
torch.cat((t1, t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

### CNN Flatten Operation Visualized - Tensor Batch Processing for Deep learning

In [51]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3], 
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

When passing through CNN, these three tensors should be conbined into a batch. A batch is expressed using one tensor. Therefore, we add another axis to represent the batch size.

In [53]:
t = torch.stack((t1, t2, t3))
t.shape

torch.Size([3, 4, 4])

In [54]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [55]:
# tensors as input to a CNN is in 4 dimensions

t = t.reshape(3, 1, 4, 4)
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [56]:
t.reshape(1, -1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [57]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [59]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [60]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [62]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

### Elementwize Operations

In [63]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)

In [64]:
t1[0]

tensor([1., 2.])

In [65]:
t1[0][0]

tensor(1.)

In [66]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [67]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [68]:
t1 + torch.tensor(
    np.broadcast_to(2, t1.shape),
    dtype=torch.float32
)

tensor([[3., 4.],
        [5., 6.]])

In [76]:
t2 = torch.tensor([2,4], dtype=torch.float32)

In [77]:
np.broadcast_to(t2.numpy(), t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [78]:
t1 + t2

tensor([[3., 6.],
        [5., 8.]])

In [79]:
t = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

In [80]:
t.eq(0)

tensor([[1, 0, 0],
        [0, 1, 0],
        [1, 0, 1]], dtype=torch.uint8)

In [81]:
t.ge(0)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)

In [82]:
t.gt(0)

tensor([[0, 1, 1],
        [1, 0, 1],
        [0, 1, 0]], dtype=torch.uint8)

In [83]:
t.lt(0)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)

In [85]:
t.le(7)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 0, 1]], dtype=torch.uint8)

In [86]:
t.abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [87]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [88]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [89]:
t.neg().abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

### Reduction Operations

A reduction operation on a tensor is an operation that reduces the number of elements contained within the tensor.


Allow operations within a single tensor.

In [90]:
t = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

In [91]:
t.sum()

tensor(33.)

In [92]:
t.numel()

9

In [93]:
t.sum().numel()

1

In [94]:
t.sum().numel() < t.numel()

True

In [95]:
t.prod()

tensor(0.)

In [96]:
t.mean()

tensor(3.6667)

In [97]:
t.std()

tensor(3.5707)

dim=n => reduces dimensions with respect to axis n (reduce the length of axis n)

In [98]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,6]
], dtype=torch.float32)

In [99]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [101]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [102]:
t[0].sum()

tensor(4.)